name: Commit validation
run-name: ${{ github.event.head_commit.message }} pushed by ${{ github.actor }}, to test and lint - $${{ github.sha }}
on:
  push:
     branches:
        - '*'                     # matches all branches
        - '!gh-pages-dont-change' # except the one for pages
jobs:
  run-bb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir, See https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - name: Base image
        uses: docker://hephaistox/gha-automaton-simulation-de:4.1.5-2-la
