erDiagram
	RANDOM-VARIABLE{
         aggregate RANDOM-VARIABLE}
  SCHEDULER{
	 aggregate SCHEDULER}
	EVENT-REGISTRY
  STATE{
		aggregate STATE}
  INDUSTRY-MODELLING{
   aggregate INDUSTRY-MODELLING}
  RC-MODELLING{
   aggregate RC-MODELLING}

DE-SIMULATION ||--|| EVENT-REGISTRY : "is using"
RANDOM-VARIABLE o{..o{ EVENT-REGISTRY : "realizes"

EVENT-REGISTRY ||--o{ SCHEDULER : "is using"
INDUSTRY-MODELLING o|--o| EVENT-REGISTRY : "produces events"
RC-MODELLING o|--o| EVENT-REGISTRY : "produces events"
EVENT-REGISTRY ||..o{ STATE : "defines modification of"
