erDiagram
    SCHEDULER-MIDDLEWARE{
	    aggregate SCHEDULER-MIDDLEWARE}
    EXECUTION-GRAPH{
	    aggregate EXECUTION-GRAPH}
    STATE {
        aggregate STATE}
	EVENT-REGISTRY{
	    aggregate EXECUTION-REGISTRY}

    SCHEDULER-MIDDLEWARE o{..o{ SCHEDULER : "is using"
    SCHEDULER-MIDDLEWARE ||..o{ SCHEDULER : "implements"
    DE-SIMULATION ||--|| SCHEDULER : "runs"
    EVENT-REGISTRY ||--o{ SCHEDULER : "is using"
    SCHEDULER o|--o| EXECUTION-GRAPH  : "feeds"
    SCHEDULER ||--o{ STATE : "generates"
