erDiagram
	SCENARIO-MANAGEMENT ||..o{ SCHEDULER : "runs"
	TIME-BASED-VARIABLE o{--o| SCHEDULER : "feeds"
  EXECUTION-GRAPH o|..o{ SCHEDULER  : "outputs"

  SCHEDULER ||--|| MIDDLEWARES : "applies"
  SCHEDULER ||--|| SNAPSHOT : "creates"
  SCHEDULER  ||--|| ORDERING : ""
  SCHEDULER  ||--|| REGISTRY : ""
